common/models/FormKewps10.php
<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\behaviors\BlameableBehavior;
use yii\db\Expression;
use common\models\People;

/**
 * This is the model class for table "KEWPS_10".
 *
 * @property string $ORDER_ID
 * @property string $ORDER_REQUIRED_DATE
 * @property string $ORDER_ITEM_ID
 * @property string $ORDER_NO
 * @property string $ORDERED_BY
 * @property string $ORDER_DATE
 * @property string $TRANSACTION_ID
 * @property string $CARD_NO
 * @property string $CODE_NO
 * @property string $DESCRIPTION
 * @property string $RQ_QUANTITY
 * @property string $APP_QUANTITY
 * @property string $CURRENT_BALANCE
 * @property string $UNIT_PRICE
 * @property string $AVERAGE_UNIT_PRICE
 * @property string $BATCH_TOTAL_PRICE
 * @property string $CREATED_DATE
 * @property integer $CREATED_BY
 * @property integer $APPROVED_BY
 * @property string $APPROVED_DATE
 */
class FormKewps10 extends \yii\db\ActiveRecord {

    /**
     * @inheritdoc
     */
    const STATUS_DELETED = 1;
    const STATUS_ACTIVE = 0;

    public function behaviors() {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'CREATED_AT',
                'updatedAtAttribute' => 'UPDATED_AT',
                'value' => date('d-M-y h.i.s a'),
            ],
            [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'CREATED_BY',
                'updatedByAttribute' => 'UPDATED_BY',
                'value' => Yii::$app->user->id,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public static function tableName() {
        return 'KEWPS_10';
    }

    public static function primaryKey() {
        return ['ORDER_ITEM_ID'];
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            [['ORDER_ID', 'ORDER_ITEM_ID', 'TRANSACTION_ID', 'RQ_QUANTITY', 'APP_QUANTITY', 'CURRENT_BALANCE', 'UNIT_PRICE', 'AVERAGE_UNIT_PRICE', 'BATCH_TOTAL_PRICE'], 'number'],
            [['CREATED_BY', 'APPROVED_BY'], 'integer'],
            [['ORDER_REQUIRED_DATE', 'ORDER_DATE'], 'string', 'max' => 7],
            [['ORDER_NO', 'ORDERED_BY'], 'string', 'max' => 20],
            [['CARD_NO', 'CODE_NO', 'DESCRIPTION'], 'string', 'max' => 255],
            [['CREATED_DATE', 'APPROVED_DATE'], 'string', 'max' => 8],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'ORDER_ID' => Yii::t('app', 'Order  ID'),
            'ORDER_REQUIRED_DATE' => Yii::t('app', 'Order  Required  Date'),
            'ORDER_ITEM_ID' => Yii::t('app', 'Order  Item  ID'),
            'ORDER_NO' => Yii::t('app', 'Order  No'),
            'ORDERED_BY' => Yii::t('app', 'Ordered  By'),
            'ORDER_DATE' => Yii::t('app', 'Order  Date'),
            'TRANSACTION_ID' => Yii::t('app', 'Transaction  ID'),
            'CARD_NO' => Yii::t('app', 'Card  No'),
            'CODE_NO' => Yii::t('app', 'Code  No'),
            'DESCRIPTION' => Yii::t('app', 'Description'),
            'RQ_QUANTITY' => Yii::t('app', 'Rq  Quantity'),
            'APP_QUANTITY' => Yii::t('app', 'App  Quantity'),
            'CURRENT_BALANCE' => Yii::t('app', 'Current  Balance'),
            'UNIT_PRICE' => Yii::t('app', 'Unit  Price'),
            'AVERAGE_UNIT_PRICE' => Yii::t('app', 'Average  Unit  Price'),
            'BATCH_TOTAL_PRICE' => Yii::t('app', 'Batch  Total  Price'),
            'CREATED_DATE' => Yii::t('app', 'Created  Date'),
            'CREATED_BY' => Yii::t('app', 'Created  By'),
            'APPROVED_BY' => Yii::t('app', 'Approved  By'),
            'APPROVED_DATE' => Yii::t('app', 'Approved  Date'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function getApprovedBy() {
        return $this->hasOne(MpspStaff::className(), ['NO_PEKERJA' => 'STAFF_NO'])
                        ->viaTable('{{%PEOPLE}}', ['ID' => 'APPROVED_BY']);
    }

    public function getCreatedBy() {
        return $this->hasOne(MpspStaff::className(), ['NO_PEKERJA' => 'STAFF_NO'])
                        ->viaTable('{{%PEOPLE}}', ['ID' => 'CREATED_BY']);
    }


    public function getRecordBy() {
        return $this->hasOne(People::className(), ['ID' => 'CREATED_BY']);
    }

    public function getUpdator() {
        return $this->hasOne(People::className(), ['ID' => 'UPDATED_BY']);
    }

}

common/models/Roles.php
<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\behaviors\BlameableBehavior;
use yii\db\Expression;
use common\models\People;

/**
 * This is the model class for table "ROLES".
 *
 * @property string $ID
 * @property string $NAME
 * @property integer $DELETED
 * @property string $DELETED_DATE
 * @property string $CREATED_AT
 * @property string $UPDATED_AT
 * @property integer $CREATED_BY
 * @property integer $UPDATED_BY
 */
class Roles extends \yii\db\ActiveRecord {

    /**
     * @inheritdoc
     */
    const STATUS_DELETED = 1;
    const STATUS_ACTIVE = 0;

    public function behaviors() {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'CREATED_AT',
                'updatedAtAttribute' => 'UPDATED_AT',
                'value' => date('d-M-y h.i.s a'),
            ],
            [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'CREATED_BY',
                'updatedByAttribute' => 'UPDATED_BY',
                'value' => Yii::$app->user->id,
            ],
        ];
    }

    public static function tableName() {
        return 'ROLES';
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
//            [['ID'], 'required'],
            [['ID'], 'number'],
            [['DELETED', 'CREATED_BY', 'UPDATED_BY'], 'integer'],
            [['DELETED_DATE', 'CREATED_AT', 'UPDATED_AT'], 'safe'],
            [['NAME'], 'string', 'max' => 255],
            [['ID'], 'unique'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'ID' => Yii::t('app', 'ID'),
            'NAME' => Yii::t('app', 'Akses'),
            'DELETED' => Yii::t('app', 'Status'),
            'DELETED_DATE' => Yii::t('app', 'Tarikh Status'),
            'CREATED_AT' => Yii::t('app', 'Tarikh Dijana'),
            'UPDATED_AT' => Yii::t('app', 'Tarikh Dikemaskini'),
            'CREATED_BY' => Yii::t('app', 'Dijana Oleh'),
            'UPDATED_BY' => Yii::t('app', 'Dikemaskini Oleh'),
        ];
    }
    
    /**
     * @inheritdoc
     */
    public function getCreator() {
        return $this->hasOne(People::className(), ['ID' => 'CREATED_BY']);
    }
    public function getUpdator() {
        return $this->hasOne(People::className(), ['ID' => 'UPDATED_BY']);
    }
}

frontend/controllers/OfficialFormController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\FormGenerator;
use common\models\Inventories;
use common\models\KewpsForm;
use common\models\Orders;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use yii\web\Controller;

class OfficialFormController extends \yii\web\Controller {

	public function actionIndex() {
		return $this->render('index');
	}

	public function actionFormGenerator() {
		$model = new FormGenerator();
		$year = \common\models\TransactionsAll::find()
		->select('EXTRACT(YEAR FROM CHECK_DATE) as YEAR')
		->distinct()->indexBy('YEAR')->asArray()->all();
		$yearList = ArrayHelper::map($year,'YEAR','YEAR');
		$monthList = [
		1 => 'Januari',
		2 => 'Febuari',
		3 => 'Mac',
		4 => 'April',
		5 => 'Mei',
		6 => 'Jun',
		7 => 'Julai',
		8 => 'Ogos',
		9 => 'September',
		10 => 'Oktober',
		11 => 'November',
		12 => 'Disember',
		];
		$formId = [
		// 3 => 'KEW.PS-3 ()',
		4 => 'KEW.PS-4 (KAD PETAK)',
		5 => 'KEW.PS-5 (SENARAI DAFTAR KAD KAWALAN STOK)',
		7 => 'KEW.PS-7 (PENENTUAN KUMPULAN STOK)',
		8 => 'KEW.PS-8 (LABEL FIFO)',
		9 => 'KEW.PS-9 (SENARAI STOK BERTARIKH LUPUT)',
		10 => 'KEW.PS-10 (BORANG PESANAN DAN PENGELUARAN STOK)',
		11 => 'KEW.PS-11 (BORANG PEMESANAN STOK)',
		13 => 'KEW.PS-13 (LAPORAN KEDUDUKAN STOK)',
		14 => 'KEW.PS-14 (LAPORAN PEMERIKSAAN / VERIFIKASI STOR)',
		17 => 'KEW.PS-17 (PENYATA PELARASAN STOK)',
		18 => 'KEW.PS-18 (PERAKUAN AMBIL ALIH)',
		];
		$inventoryList = Inventories::find()->andFilterWhere(['DELETED' => 0])->asArray()->all();
		$inventoriesArray = ArrayHelper::map($inventoryList, 'ID', 'DESCRIPTION');
		$orderList = Orders::find()
		->andFilterWhere(['DELETED' => 0])
		// ->andFilterWhere(['APPROVED' => 1])
		->asArray()->all();
		$ordersArray = ArrayHelper::map($orderList, 'ID', 'ORDER_NO');
		$formName = new FormGenerator();
//        var_dump($model);die();
		if ($model->load(Yii::$app->request->post())) {
			// var_dump(Yii::$app->request->post());die();
			if ($model->FORM_ID == 3) {
				// KewpsForm::pdfKewps4(
				//     $id = $model->INVENTORY_ID,
				//     $year = $model->YEAR,
				//     $month = $model->MONTH
				//     );
			} else if ($model->FORM_ID == 4) {
				KewpsForm::pdfKewps4(
					$id = $model->INVENTORY_ID,
					$year = $model->YEAR,
					$month = $model->MONTH,
					// $printAll = $model->printAll
					$printAll = 0
					);
			} else if ($model->FORM_ID == 5) {
				KewpsForm::pdfKewps5(
					$id = $model->INVENTORY_LIST
					);
			} else if ($model->FORM_ID == 7) {
				KewpsForm::pdfKewps7(
					$id = $model->INVENTORY_LIST,
					$year = $model->YEAR
					);
			} else if ($model->FORM_ID == 8) {
				KewpsForm::pdfKewps8(
					$id = $model->INVENTORY_LIST
					);
			} else if ($model->FORM_ID == 9) {
				KewpsForm::pdfKewps9(
					$id = $model->INVENTORY_LIST
					);
			} else if ($model->FORM_ID == 10) {
				KewpsForm::pdfKewps10(
					$id = $model->ORDER_ID
					);
			} else if ($model->FORM_ID == 11) {
				KewpsForm::pdfKewps11(
					$id = $model->ORDER_ID
					);
			} else if ($model->FORM_ID == 13) {
				KewpsForm::pdfKewps13(
					$year = $model->YEAR
					);
			} else if ($model->FORM_ID == 14) {
				KewpsForm::pdfKewps14(
					$id = $model->INVENTORY_LIST,
					$year = $model->YEAR
					);
			} else if ($model->FORM_ID == 17) {
				KewpsForm::pdfKewps17(
					$id = $model->INVENTORY_LIST
					);
			} else if ($model->FORM_ID == 18) {
				KewpsForm::pdfKewps18(
					$id = $model->INVENTORY_LIST
					);
			}
		}

		return $this->render('form-generator', [
			'model' => $model,
			'formId' => $formId,
			'yearList' => $yearList,
			'monthList' => $monthList,
			'ordersArray' => $ordersArray,
			'inventoriesArray' => $inventoriesArray,
			]);
	}
	public function actionFormOptions() {
		$out = [];
		if (isset($_POST['depdrop_parents'])) {
			$parents = $_POST['depdrop_parents'];
			if ($parents != null) {
				$form_id = $parents[0];
				if ($form_id == 3) {
					$out = \common\models\Inventories::find()
					// ->select('ID,CODE_NO,CARD_NO,DESCRIPTION,QUANTITY,LOCATION')
					->select('ID as id,DESCRIPTION as name')
					->asArray()->all();
					// $out  = ArrayHelper::index($out,'ID');

				}
				if ($form_id == 4) {
					$out = \common\models\Orders::find()
					->select('ID as id,ORDER_NO as name')
					// ->select('ORDERS.ID,ORDER_NO,ARAHAN_KERJA_ID,APPROVED,VEHICLE_ID')
					// ->with('arahanKerja','vehicle')
					->asArray()->all();
				}
				echo Json::encode(['output' => $out, 'selected' => '']);
				return;
			}
		}
		echo Json::encode(['output' => '', 'selected' => '']);
	}

	public function actionPdfKewps3($id = null) {
		var_dump('note created yet');die();
	}
	public function actionPdfKewps4($id = null) {
		var_dump($id);die();
		KewpsForm::pdfKewps4($id);
	}

	public function actionPdfKewps5($id = null) {
		KewpsForm::pdfKewps5($id);
	}

	public function actionPdfKewps7($id = [145, 144]) {
		KewpsForm::pdfKewps7($id);
	}

	public function actionPdfKewps8($id = null) {
		KewpsForm::pdfKewps8($id);
	}

	public function actionPdfKewps82($id = null) {
		KewpsForm::pdfKewps82($id);
	}
	public function actionPdfKewps9($id = null) {
		KewpsForm::pdfKewps9($id);
	}

	public function actionPdfKewps10($id = null) {
		KewpsForm::pdfKewps10($id);
	}
	public function actionPdfKewps11($id = null) {
		KewpsForm::pdfKewps11($id);
	}

	public function actionPdfKewps13($id = null, $year = null) {
		KewpsForm::pdfKewps13($id);
	}

	public function actionPdfKewps14($id = null) {
		KewpsForm::pdfKewps14($id);
	}

	public function actionPdfKewps17($id = null) {
		KewpsForm::pdfKewps17($id);
	}

	public function actionPdfKewps18($id = null) {
		KewpsForm::pdfKewps18($id);
	}

}

frontend/views/official-form/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;
    // var_dump(url::to(['/official-form/form-options']));die();
$script = <<<JS
// $(document).on('submit', 'form[data-pjax]', function(event) {

//   $.pjax.submit(event, '#pjax-container')
// });
$('#formgenerator-form_id').on('change', function() {
    var formId = $(this).val();
//  iv_id,year,month
    if (formId == 0) {
        $('#inventory_section').hide(800);
        $('#inventories_section').show(800);
        $('#order_section').hide(800);
        $('#timeframe_section').show(800);
        $('#month_section').show(800);
//  iv_id,year,month
    } else if (formId == 4) {
        $('#inventory_section').show(800);
        $('#inventories_section').hide(800);
        $('#order_section').hide(800);
        $('#timeframe_section').show(800);
        $('#month_section').show(800);
//  o_id,year,month
    } else if (formId == 0) {
        $('#inventory_section').hide(800);
        $('#inventories_section').hide(800);
        $('#order_section').show(800);
        $('#timeframe_section').show(800);
        $('#month_section').show(800);
//  o_id
    } else if ($.inArray(formId , ["10","11"] ) > -1) {
        // alert('success');
        $('#inventory_section').hide(800);
        $('#inventories_section').hide(800);
        $('#order_section').show(800);
        $('#timeframe_section').hide(800);
        $('#month_section').hide(800);
//  iv_id
    } else if ($.inArray(formId , ["5","8","9","17","18"] ) > -1) {
        $('#inventory_section').hide(800);
        $('#inventories_section').show(800);
        $('#order_section').hide(800);
        $('#timeframe_section').hide(800);
        $('#month_section').hide(800);
//  o_id,year
    } else if (formId == 0) {
        $('#inventory_section').hide(800);
        $('#inventories_section').hide(800);
        $('#order_section').show(800);
        $('#timeframe_section').show(800);
        $('#month_section').hide(800);
//  iv_id,year
    } else if ($.inArray(formId , ["7","14"] ) > -1) {
        $('#inventory_section').hide(800);
        $('#inventories_section').show(800);
        $('#order_section').hide(800);
        $('#timeframe_section').show(800);
        $('#month_section').hide(800);
//  year
    } else if (formId == 13) {
        $('#inventory_section').hide(800);
        $('#inventories_section').hide(800);
        $('#order_section').hide(800);
        $('#timeframe_section').show(800);
        $('#month_section').hide(800);
//  hide all
    } else {
        $('#inventory_section').hide(800);
        $('#inventories_section').hide(800);
        $('#order_section').hide(800);
        $('#timeframe_section').hide(800);
        $('#month_section').hide(800);
    }
});
JS;

/* @var $this yii\web\View */
/* @var $model common\models\OrderItems */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="order-items-form">

    <?php
    // Pjax::begin();
    $this->registerJs($script);
    ?>
    <?php $form = ActiveForm::begin(['id' => 'configform']);?>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-4">
                <?php echo $form->field($model, 'FORM_ID')->widget(kartik\select2\Select2::className(),
                    [
                    'data'          => $formId,
                        // 'theme' => 'default',
                    'options'       => ['placeholder' => 'Select an inventory ...'],
                    'pluginOptions' => [
                    'allowClear' => true,
                    ]
                    ]);
                    ?>
                </div>
            </div>
            <div class="row" id="inventory_section" style="display: none">
                <div class="col-md-4">
                    <?=
                    $form->field($model, 'INVENTORY_ID')->widget(kartik\select2\Select2::className(), [
                        'data'          => $inventoriesArray,
    // 'theme' => 'default',
                        'options'       => ['placeholder' => 'Select an inventory ...'],
                        'pluginOptions' => [
                        'allowClear' => true,
                        ],
                        ]);
                        ?>
                    </div>
                </div>
                <div class="row" id="inventories_section" style="display: none">
                    <div class="col-md-4">
                        <?=
                        $form->field($model, 'INVENTORY_LIST')->widget(kartik\select2\Select2::className(),
                            [
                            'data'          => $inventoriesArray,
        // 'theme' => 'default',
                            'options'       => ['placeholder' => 'Select an inventory ...', 'multiple' => true],
                            'pluginOptions' => [
                            'allowClear' => true,
                            ],
                            ]);
                            ?>
                        </div>
                    </div>
                    <div class="row" id="order_section" style="display: none">
                        <div class="col-md-4">
                            <?=
                            $form->field($model, 'ORDER_ID')->widget(kartik\select2\Select2::className(),
                                [
                                'data'          => $ordersArray,
        // 'theme' => 'default',
                                'options'       => ['placeholder' => 'Select an inventory ...'],
                                'pluginOptions' => [
                                'allowClear' => true,
                                ],
                                ]);
                                ?>
                            </div>
                        </div>
                        <div class="row" id="timeframe_section" style="display: none">
                            <div class="col-md-4" id="year_section">
                                <?=
                                $form->field($model, 'YEAR')->widget(kartik\select2\Select2::className(),
                                    [
                                    'data'          => $yearList,
        // 'theme' => 'default',
                                    'options'       => ['placeholder' => 'Select an inventory ...'],
                                    'pluginOptions' => [
                                    'allowClear' => true,
                                    ],
                                    ]);
                                    ?>
                                </div>
                                <div class="col-md-4" id="month_section" style="display: none">
                                    <?=
                                    $form->field($model, 'MONTH')->widget(kartik\select2\Select2::className(),
                                        [
                                        'data'          => $monthList,
        // 'theme' => 'default',
                                        'options'       => ['placeholder' => 'Select an inventory ...'],
                                        'pluginOptions' => [
                                        'allowClear' => true,
                                        ],
                                        ]);
                                        ?>
                                    </div>
                                </div>
                                <div>
                                    <?=Html::a(Yii::t('app', 'Isi Semula'), ['/official-form/form-generator'], ['id'=>'reset','class' => 'btn btn-default']);
                                    ?>
                                    <?=Html::submitButton(Yii::t('app', 'Cetak'), ['class' => 'btn btn-primary', 'formtarget' => '_blank']);
                                    ?>
                                </div>
                            </div>
                            <?php ActiveForm::end();?>
                            <?php
                            // Pjax::end();
                            ?>
                        </div>

frontend/views/official-form/_kewps11.php
<div class="box-body table-responsive">
    <div>
        <!--<p><span>Pekeliling Perbendaharaan Malaysia</span><span class="pull-right">AM 6.5 Lampiran A</span></p>-->
        <p class="pull-right form-lampiran"><strong>LAMPIRAN B</strong><br><strong>KEW.PS-11</strong></p>
        <p class="pull-right form-lampiran"><strong>No. Permohonan : <?= $model->ORDER_NO ?></strong></p>
        <!--<div class="clearfix"></div>-->
        <p class="text-center form-name"><strong>BORANG PEMESANAN STOK</strong></p>
        <table class="kv-grid-table table table-hover table-bordered table-condensed kv-table-wrap">
        <!--<table bordered>-->
            <thead>
                <tr>
                    <th class="col-1 vertical-align-top text-center text-center default" rowspan="2">Bil</th>
                    <th class="col-2 vertical-align-top text-center text-center default" colspan="3">Pemohonan</th>
                    <th class="col-2 vertical-align-top text-center text-center default" colspan="2">Pegawai Pelulus</th>
                    <th class="no-border-right text-center vertical-align-top text-center text-center default" rowspan="2">Catatan</th>
                </tr>
                <tr>
                    <th class="col-1 vertical-align-top text-center text-center default" colspan="2">Perihal Stok</th>
                    <th class="col-2 vertical-align-top text-center text-center default" >Kuantiti Dipesan</th>
                    <th class="col-3 vertical-align-top text-center text-center default" >Kuantiti Diluluskan</th>
                    <th class="col-4 vertical-align-top text-center text-center default" >Baki Kuantiti Dipesan</th>
                </tr>
            </thead>
            <tbody>
                <?php if (sizeof($items) >= 1) { ?>
                    <?php foreach ($items as $i => $item) { ?>
                        <tr>
                            <td class="center"><?= $i + 1 ?></td>
                            <td class="" colspan="2"><?= $item->inventory->DESCRIPTION ?></td>
                            <td class="center" ><?= $item->RQ_QUANTITY ?></td>
                            <td class="center" ><?= $item->APP_QUANTITY ?></td>
                            <td class="center" ><?= $item->CURRENT_BALANCE ?></td>
                            <td class=""></td>
                        </tr>
                    <?php } ?>
                    <?php for ($j = sizeof($items); $j < 5; $j++) { ?>
                        <tr>
                            <td class="center"> <?= $j + 1 ?></td>
                            <td class="col-2 pull-left" colspan="2"> </td>
                            <td class="col-2 pull-left" > </td>
                            <td class="col-2 pull-left" > </td>
                            <td class="col-2 pull-left" > </td>
                            <td class="col-10 pull-left">&nbsp;</td>
                        </tr>
                    <?php } ?>
                <?php } else { ?>
                    <?php for ($j = 0; $j < 5; $j++) { ?>
                        <tr>
                            <td class="center"> <?= $j + 1 ?></td>
                            <td class="col-2 pull-left" colspan="2"> </td>
                            <td class="col-2 pull-left" > </td>
                            <td class="col-2 pull-left" > </td>
                            <td class="col-2 pull-left" > </td>
                            <td class="col-10 pull-left">&nbsp;</td>
                        </tr>
                    <?php } ?>
                <?php } ?>
            <tbody>
            <tfoot>
                <tr>
                    <td class="no-border-bottom" colspan="4">
                        <br><br>
                        <br><br>
                    </td>
                    <td class="no-border-bottom" colspan="3">
                        <br><br>
                        <br><br>
                    </td>
                </tr>
                <tr>
                    <td class="no-border-top" colspan="4">
                        <p>......................</p>
                        <p>(Tandatangan Pemohon)</p>
                    </td>
                    <td class="no-border-top" colspan="3">
                        <p>......................</p>
                        <p>(Tandatangan Pemohon)</p>
                    </td>
                </tr>
                <tr>
                    <td class="no-border-right" colspan="2">NAMA</td>
                    <td class="no-border-left" colspan="2">: <?= $model->ORDERED_BY ?></td>
                    <td class="no-border-right">NAMA</td>
                    <td class="no-border-left" colspan="2">: <?= $model->approvedBy->NAME ?></td>
                </tr>
                <tr>
                    <td class="no-border-right" colspan="2">JAWATAN</td>
                    <td class="no-border-left" colspan="2">:</td>
                    <td class="no-border-right">JAWATAN</td>
                    <td class="no-border-left" colspan="2">: <?= $model->approvedBy->mpspProfile->JAWATAN ?></td>
                </tr>
                <tr>
                    <td class="no-border-right" colspan="2">TARIKH</td>
                    <td class="no-border-left" colspan="2">: <?= $model->ORDER_DATE ?></td>
                    <td class="no-border-right">TARIKH</td>
                    <td class="no-border-left" colspan="2">: <?= $model->APPROVED_AT ?></td>
                </tr>
            </tfoot>
        </table><br>
        <table class="kv-grid-table table table-hover table-bordered table-condensed kv-table-wrap">
            <tbody>
                <tr>
                    <td class="no-border-bottom" colspan="4">
                        <br><br>
                        <br><br>
                    </td>
                    <td class="no-border-bottom" colspan="3">
                        <br><br>
                        <br><br>
                    </td>
                </tr>
                <tr>
                    <td class="no-border-top" colspan="4">
                        <p>......................</p>
                        <p>(Tandatangan Pemohon)</p>
                    </td>
                    <td class="no-border-top" colspan="3">
                        <p>......................</p>
                        <p>(Tandatangan Pemohon)</p>
                    </td>
                </tr>
                <tr>
                    <td class="no-border-right" colspan="2">NAMA</td>
                    <td class="no-border-left" colspan="2">: <?= $model->ORDERED_BY ?></td>
                    <td class="no-border-right">NAMA</td>
                    <td class="no-border-left" colspan="2">: <?= $model->approvedBy->NAME ?></td>
                </tr>
                <tr>
                    <td class="no-border-right" colspan="2">JAWATAN</td>
                    <td class="no-border-left" colspan="2">:</td>
                    <td class="no-border-right">JAWATAN</td>
                    <td class="no-border-left" colspan="2">: <?= $model->approvedBy->mpspProfile->JAWATAN ?></td>
                </tr>
                <tr>
                    <td class="no-border-right" colspan="2">TARIKH</td>
                    <td class="no-border-left" colspan="2">: <?= $model->ORDER_DATE ?></td>
                    <td class="no-border-right">TARIKH</td>
                    <td class="no-border-left" colspan="2">: <?= $model->APPROVED_AT ?></td>
                </tr>
            </tbody>>
        </table>

    </div>
</div>

frontend/views/official-form/_kewps7_3.php
            <tfoot>
                <tr>
                    <td class="foot-note-col-1 foot-note-vertical-align-top text-center" colspan="5">JUMLAH KESELURUHAN</td>
                    <td class="foot-note-col-2 foot-note-vertical-align-top text-center" colspan="3">
                        CATATAN : <br>
                        Kumpulan A : 30%<br>
                        Kumpulan B : 70%<br>
                    </td>
                </tr>
            </tfoot>
        </table>
        <p><i>*Seksyen stok seperti Seksyen Alat Tulis, Elektrik, Alat Ganti, Makmal, Bahan Kimia dan Ubat-Ubatan</i></p>
    </div>
</div>