frontend/controllers/InventoryItemsController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\InventoryItems;
use common\models\InventoriesCheckIn;
use common\models\Transactions;
use common\models\Inventories;
use common\models\InventoryItemsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\components\AccessRule;
use kartik\widgets\Alert;
use kartik\widgets\Growl;
use yii\db\Expression;
use yii\db\Exception;

/**
 * InventoryItemsController implements the CRUD actions for InventoryItems model.
 */
class InventoryItemsController extends Controller {

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                    'recover' => ['POST'],
                    'delete-multiple' => ['POST'],
                    'delete-permanent' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'ruleConfig' => [
                    'class' => AccessRule::className(),],
                'only' => ['create', 'update', 'index', 'view',
                    'delete', 'delete-permanent', 'recover'],
                'rules' => [
                    [
                        'actions' => ['delete-permanent'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['create', 'update', 'delete', 'recover'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['index', 'view'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * Lists all InventoryItems models.
     * @return mixed
     */
    public function actionIndex() {
        $searchModel = new InventoryItemsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->query->andWhere(['CHECKOUT_TRANSACTION_ID' => null]);
        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
//                    'data' => $data,
        ]);
    }

    public function actionPrintInventoryCode() {
        InventoryItems::printSku([34246,34242]);
    }
    public function actionPrintSkuById($id,$printInventoryCode) {
        // var_dump($printInventoryCode);die();
        InventoryItems::printSkuById($id,$printInventoryCode);
    }
    public function actionPrintSku($sku,$printInventoryCode = 0) {
        InventoryItems::printSku($sku,$printInventoryCode = 0);
    }

    public function actionIndex2() {
        $searchModel = new InventoryItemsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index2', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single InventoryItems model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id) {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
//return $this->redirect(['index']);
    }

    /**
     * Creates a new InventoryItems model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new InventoryItems();

        if ($model->load(Yii::$app->request->post())) {
            if ($model->save()) {
                \Yii::$app->session->setFlash('success', [
                    'type' => Growl::TYPE_SUCCESS,
                    'duration' => 3000,
                    'icon' => 'glyphicon glyphicon-ok-sign',
                    'title' => ' Proses BERJAYA',
                    'message' => ' Data berjaya ditambah.',
                    'positonY' => 'top',
                    'positonX' => 'right'
                ]);
            } else {
                \Yii::$app->session->setFlash('error', [
                    'type' => Growl::TYPE_DANGER,
                    'duration' => 3000,
                    'icon' => 'glyphicon glyphicon-remove-sign',
                    'title' => ' Proses GAGAL.',
                    'message' => ' Data tidak berjaya ditambah.',
                    'positonY' => 'top',
                    'positonX' => 'right'
                ]);
            }
            return $this->redirect(['view', 'id' => $model->ID]);
//return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing InventoryItems model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            if ($model->save()) {
                \Yii::$app->session->setFlash('success', [
                    'type' => Growl::TYPE_SUCCESS,
                    'duration' => 3000,
                    'icon' => 'glyphicon glyphicon-ok-sign',
                    'title' => ' Proses BERJAYA',
                    'message' => ' Data berjaya dikemaskini.',
                    'positonY' => 'top',
                    'positonX' => 'right'
                ]);
            } else {
                \Yii::$app->session->setFlash('error', [
                    'type' => Growl::TYPE_DANGER,
                    'duration' => 3000,
                    'icon' => 'glyphicon glyphicon-remove-sign',
                    'title' => ' Proses GAGAL.',
                    'message' => ' Data tidak berjaya dikemaskini.',
                    'positonY' => 'top',
                    'positonX' => 'right'
                ]);
            }
            return $this->redirect(['view', 'id' => $model->ID]);
//return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing InventoryItems model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id) {
//            start operation
        $dbtransac = Yii::$app->db->beginTransaction();
        try {
            $model = $this->findInventoryItemInStore($id);
//        check if items still in store, otherwise abort process
            if (empty($model)) {
                Throw new Exception(' Item telah dikeluarkan dari stor / Item tiada dalam stor.');
            }
            $model->DELETED = '1';
//                error if item cannot be update
            if (!$model->save()) {
                Throw new Exception(' Data tidak berjaya dihapuskan.');
            }
//                error if related inventory quantity cannot be update
            if (!Inventories::updateQuantity($model->inventory->ID)) {
                Throw new Exception('');
            }
//                error if related checkin transaction quantity and total price cannot be update
            if (!InventoriesCheckIn::updateQuantityAndTotalPriceCheckIn($model->CHECKIN_TRANSACTION_ID)) {
                Throw new Exception('');
            }
//                commit operation
            $dbtransac->commit();
            Yii::$app->notify->success(' Data berjaya dihapuskan.');
        } catch (\Exception $e) {
//                rollback operation on failure
            $dbtransac->rollback();
            Yii::$app->notify->fail($e->getMessage());
        }
//        redirect to previous page
        return $this->redirect(\Yii::$app->request->referrer);
    }

    public function actionRecover($id) {
        $dbtransac = Yii::$app->db->beginTransaction();
        try {
            $model = $this->findInventoryItemInStore($id);
            if (empty($model)) {
                Throw new Exception(' Item telah dikeluarkan dari stor / Item tiada dalam stor.');
            }
            $model->DELETED = '0';
//                error if item cannot be update
            if (!$model->save()) {
                Throw new Exception(' Data tidak berjaya dikembalikan.');
            }
//                error if related inventory quantity cannot be update
            if (!Inventories::updateQuantity($model->inventory->ID)) {
                Throw new Exception('');
            }
//                error if related checkin transaction quantity and total price cannot be update
            if (!InventoriesCheckIn::updateQuantityAndTotalPriceCheckIn($model->CHECKIN_TRANSACTION_ID)) {
                Throw new Exception('');
            }
//                commit operation
            $dbtransac->commit();
            Yii::$app->notify->success(' Data berjaya dikembalikan.');
        } catch (\Exception $e) {
//                rollback operation on failure
            $dbtransac->rollback();
            Yii::$app->notify->fail($e->getMessage());
        }
//        redirect to previous page
        return $this->redirect(\Yii::$app->request->referrer);
    }

    public function actionDeletePermanent($id) {
        $dbtransac = Yii::$app->db->beginTransaction();
        try {
            $model = $this->findInventoryItemInStore($id);
            if (empty($model)) {
                Throw new Exception('  Data tidak berjaya dihapuskan. Item telah dikeluarkan dari stor.');
            }

frontend/views/inventory-items/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\InventoryItems */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="inventory-items-form">

    <?php $form = ActiveForm::begin(); ?>
    <div class="panel-body">
        <div class="row">
            <!--            <div class="col-md-4">
            <?= $form->field($model, 'INVENTORY_ID')->textInput() ?>
                        </div>-->
            <div class="col-md-4">
                <?= $form->field($model, 'CHECKIN_TRANSACTION_ID')->textInput(['readOnly' => true]) ?>
            </div>
            <div class="col-md-4">
                <?= $form->field($model, 'CHECKOUT_TRANSACTION_ID')->textInput(['readOnly' => true]) ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <?= $form->field($model, 'SKU')->textInput(['maxlength' => true]) ?>
            </div>
            <div class="col-md-4">
                <?= $form->field($model, 'UNIT_PRICE')->textInput(['maxlength' => true]) ?>
            </div>

        </div>
        <div>
            <?= Html::a(Yii::t('app', 'Batal'), Yii::$app->request->referrer, ['class' => 'btn btn-default']) ?>
            <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Kemaskini'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/inventory-items/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\InventoryItemsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="inventory-items-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'ID') ?>

    <?= $form->field($model, 'INVENTORY_ID') ?>

    <?= $form->field($model, 'CHECKIN_TRANSACTION_ID') ?>

    <?= $form->field($model, 'CHECKOUT_TRANSACTION_ID') ?>

    <?= $form->field($model, 'SKU') ?>

    <?php // echo $form->field($model, 'UNIT_PRICE') ?>

    <?php // echo $form->field($model, 'CREATED_AT') ?>

    <?php // echo $form->field($model, 'UPDATED_AT') ?>

    <?php // echo $form->field($model, 'CREATED_BY') ?>

    <?php // echo $form->field($model, 'UPDATED_BY') ?>

    <?php // echo $form->field($model, 'DELETED') ?>

    <?php // echo $form->field($model, 'DELETED_AT') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/inventory-items/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\InventoryItems */

$this->title = Yii::t('app', 'Create Inventory Items');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Inventory Items'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="inventory-items-create">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h4><i class="fa fa-download"> </i><?= Html::encode($this->title) ?></h4>
        </div>

        <?= $this->render('_form', [
        'model' => $model,
        ]) ?>

    </div>
</div>

frontend/views/inventory-items/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $searchModel common\models\InventoryItemsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Inventory Items');
$this->params['breadcrumbs'][] = $this->title;

$title = empty($this->title) ? Yii::t('app', 'Report') : $this->title . ' Report';
$pdfHeader = [
    'L' => [
        'content' => Yii::t('app', 'Sistem e-Store MPSP'),
        'font-size' => 8,
        'font-weight' => '600',
        'color' => '#333333'
    ],
    'C' => [
        'content' => $title,
        'font-size' => 16,
//        'font-weight' => 'bold',
        'color' => '#333333'
    ],
    'R' => [
        'content' => Yii::t('app', 'Generated') . ': ' . date("D, d-M-Y g:i a T"),
        'font-size' => 8,
        'color' => '#333333'
    ]
];
$pdfFooter = [
    'L' => [
        'content' => Yii::t('app', "Copyright © Muzzam Teknologi Sdn Bhd"),
        'font-size' => 8,
        'font-style' => 'B',
        'color' => '#999999'
    ],
    'R' => [
        'content' => '[ {PAGENO} ]',
        'font-size' => 10,
        'font-style' => 'B',
        'font-family' => 'serif',
        'color' => '#333333'
    ],
    'line' => true,
];
$pdf = [
    'label' => Yii::t('app', 'PDF'),
    'icon' => 'file-pdf-o',
    'iconOptions' => ['class' => 'text-danger'],
    'showHeader' => true,
    'showPageSummary' => true,
    'showFooter' => true,
    'showCaption' => true,
    'filename' => Yii::t('app', 'grid-export'),
    'alertMsg' => Yii::t('app', 'The PDF export file will be generated for download.'),
    'options' => ['title' => Yii::t('app', 'Portable Document Format')],
    'mime' => 'application/pdf',
    'config' => [
        'mode' => 'c',
        'format' => 'A4-L',
        'destination' => 'D',
        'marginTop' => 20,
        'marginBottom' => 20,
        'cssInline' => '.kv-wrap{padding:20px;}' .
        '.kv-align-center{text-align:center;}' .
        '.kv-align-left{text-align:left;}' .
        '.kv-align-right{text-align:right;}' .
        '.kv-align-top{vertical-align:top!important;}' .
        '.kv-align-bottom{vertical-align:bottom!important;}' .
        '.kv-align-middle{vertical-align:middle!important;}' .
        '.kv-page-summary{border-top:4px double #ddd;font-weight: bold;}' .
        '.kv-table-footer{border-top:4px double #ddd;font-weight: bold;}' .
        '.kv-table-caption{font-size:1.5em;padding:8px;border:1px solid #ddd;border-bottom:none;}',
        'methods' => [
            'SetHeader' => [
                ['odd' => $pdfHeader, 'even' => $pdfHeader]
            ],
            'SetFooter' => [
                ['odd' => $pdfFooter, 'even' => $pdfFooter]
            ],
        ],
        'options' => [
            'title' => $title,
            'subject' => Yii::t('app', 'PDF export generated by kartik-v/yii2-grid extension'),
            'keywords' => Yii::t('app', 'krajee, grid, export, yii2-grid, pdf')
        ],
        'contentBefore' => '',
        'contentAfter' => ''
    ]
];
?>
<div class="inventory-items-index">
</div>
    <div class="inventory-items-index">

    <?php Pjax::begin(); ?>            <?=
    GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'headerRowOptions' => ['class' => 'kartik-sheet-style'],
        'filterRowOptions' => ['class' => 'kartik-sheet-style'],
        'rowOptions' => function($model) {
    if ($model->CHECKOUT_TRANSACTION_ID) {
        return ['class' => 'danger'];
    } else {
        return ['class' => 'info'];
//        return null;
    }
},
        'summary' => 'Memaparkan <b>{begin, number}-{end, number}</b> daripada <b>{totalCount, number}</b> {totalCount, plural, one{data} other{data}}.',
        'pjax' => true, // pjax is set to always true for this demo
        // set your toolbar
        'toolbar' => [
            ['content' =>
                Html::a('<i class="glyphicon glyphicon-plus"></i>', ['create'], ['class' => 'btn btn-success', 'title' => Yii::t('app', 'Create inventory-items'),])//. ' ' .
            //                Html::a(Yii::t('app', 'Create Categories'), ['create'], ['class' => 'btn btn-success']) //. ' ' .
            //                Html::button('<i class="glyphicon glyphicon-plus"></i>', ['type' => 'button', 'title' => Yii::t('app', 'Add Book'), 'class' => 'btn btn-success', 'onclick' => 'alert("This will launch the book creation form.\n\nDisabled for this demo!");']) . ' ' .
            ],
            '{export}',
            '{toggleData}',
        ],
        // set export properties
        'exportConfig' => [
            'pdf' => $pdf,
            'csv' => '{csv}',
            'xls' => '{xls}',
        ],
        'export' => [
            'fontAwesome' => true,
            'target' => '_self',
        ],
        // parameters from the demo form
        'bordered' => true,
        'striped' => true,
        'condensed' => true,
        'responsive' => true,
        'hover' => true,
        //        'showPageSummary' => true,
        'panel' => [
            'type' => GridView::TYPE_PRIMARY,
            'heading' => $this->title,
        ],
        'responsiveWrap' => false,
        'persistResize' => false,
        //        'exportConfig' => $exportConfig,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            [
                'attribute' => 'ID',
                'hAlign' => 'center', 'vAlign' => 'middle',
            ],
            [
                'attribute' => 'inventory.DESCRIPTION',
                'hAlign' => 'center', 'vAlign' => 'middle',
            ],
            [
                'attribute' => 'CHECKIN_TRANSACTION_ID',
                'hAlign' => 'center', 'vAlign' => 'middle',
            ],
            [
                'attribute' => 'CHECKOUT_TRANSACTION_ID',
                'hAlign' => 'center', 'vAlign' => 'middle',
            ],
            [
                'attribute' => 'SKU',
                'hAlign' => 'center', 'vAlign' => 'middle',
            ],
            [
                'attribute' => 'UNIT_PRICE',
                'hAlign' => 'center', 'vAlign' => 'middle',
            ],
            [
                'attribute' => 'DELETED',
                'hAlign' => 'center', 'vAlign' => 'middle',
            ],
            /* [
              'attribute'=>'CREATED_AT',
              'hAlign' => 'center', 'vAlign' => 'middle',
              ], */
            /* [
              'attribute'=>'UPDATED_AT',
              'hAlign' => 'center', 'vAlign' => 'middle',
              ], */
            /* [
              'attribute'=>'CREATED_BY',
              'hAlign' => 'center', 'vAlign' => 'middle',
              ], */
            /* [
              'attribute'=>'UPDATED_BY',
              'hAlign' => 'center', 'vAlign' => 'middle',
              ], */
            /* [
              'attribute'=>'DELETED_AT',
              'hAlign' => 'center', 'vAlign' => 'middle',
              ], */
            [
                'class' => 'kartik\grid\ActionColumn',
                'visible' => Yii::$app->user->isAdmin || Yii::$app->user->isPegawaiStor,
                'template' => '{print-sku} {view} {update} {delete} {recover}',
                'viewOptions' => ['title' => 'View', 'data-toggle' => 'tooltip'],
                'updateOptions' => ['title' => 'Update', 'data-toggle' => 'tooltip'],
                'buttons' => [
                    'print-sku' => function ($url, $model) {
                        if ($model->DELETED === 0) {
                            return Html::a('<span class="glyphicon glyphicon-barcode"></span>', ['/inventory-items/print-sku-by-id','id'=>$model->ID,'printInventoryCode'=>true], ['title' => Yii::t('yii', 'Print SKU Barcode'), 'data-toggle' => 'tooltip', 'data-pjax' => 0,'target'=>'_blank']);
                        }
                    },
                    'recover' => function ($url, $model) {
                        if ($model->DELETED === 1) {
                            return Html::a('<span class="glyphicon glyphicon-refresh"></span>', $url, ['title' => Yii::t('yii', 'Recover'), 'data-toggle' => 'tooltip',
                                        'data-method' => 'post']);
                        }
                    },
                            'delete' => function ($url, $model) {
                        if ($model->DELETED === 0) {
                            return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, ['title' => Yii::t('yii', 'Delete'), 'data-toggle' => 'tooltip',
                                        'data-method' => 'post']);
                        }
                    },
                        ],
                    ],
                    [
                        'header' => 'Permanent Delete',
                        'class' => 'kartik\grid\ActionColumn',
                        'template' => '{delete-permanent}',
                        'buttons' => [
                            'delete-permanent' => function ($url, $model) {
//                                if (empty($model->CHECKOUT_TRANSACTION_ID)) {
                                return Html::a('<span class="glyphicon glyphicon-trash" style="color:red;"></span>', $url, [
                                            'title' => Yii::t('yii', 'Permanent Delete'), 'data-toggle' => 'tooltip',
                                            'data-method' => 'post']);
//                                }
                            }
                                ],
                                'visible' => Yii::$app->user->isAdmin
                            ],
                        ],
                    ]);
                    ?>
                    <?php Pjax::end(); ?></div>

frontend/views/inventory-items/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\InventoryItems */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'Inventory Items',
]) . $model->ID;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Inventory Items'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->ID, 'url' => ['view', 'id' => $model->ID]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Kemaskini');
?>
<div class="inventory-items-update">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h4><i class="fa fa-download"> </i><?= Html::encode($this->title) ?></h4>
        </div>

        <?= $this->render('_form', [
        'model' => $model,
        ]) ?>

    </div>
</div>

frontend/views/inventory-items/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

//var_dump(Yii::$app->request->referrer);
//var_dump(preg_match('/*inventory-items*/', Yii::$app->request->referrer));
//die();
/* @var $this yii\web\View */
/* @var $model common\models\InventoryItems */

$this->title = $model->ID;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Inventory Items'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="box box-info inventory-items-view">
    <div class="box-header with-border">
        <h3 class="box-title"><strong><i class="fa fa-book margin-r-5 text-blue"></i>inventory-items : <?= Html::encode($this->title) ?></strong></h3>
    </div>
    <div class="box-body">
        <p>
            <?= Html::a(Yii::t('app', 'Kembali'), Yii::$app->request->referrer, ['class' => 'btn btn-default']) ?>
            <?= Html::a(Yii::t('app', 'Kemaskini'), ['update', 'id' => $model->ID], ['class' => 'btn btn-primary']) ?>
            <?= Html::a(Yii::t('app', 'Cetak Barkod Inventori & SKU'), ['/inventory-items/print-sku-by-id','id'=>$model->ID,'printInventoryCode'=>true], ['class' => 'btn btn-info','target'=>'_blank']) ?>
            <?= Html::a(Yii::t('app', 'Cetak Barkod Inventori'), ['/inventories/print-barcode','id'=>$model->inventory->ID], ['class' => 'btn btn-info','target'=>'_blank']) ?>
            <?= Html::a(Yii::t('app', 'Cetak Barkod SKU'), ['/inventory-items/print-sku-by-id','id'=>$model->ID,'printInventoryCode'=>false], ['class' => 'btn btn-info','target'=>'_blank']) ?>
            <?=
            Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->ID], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                    'method' => 'post',
                ],
            ])
            ?>
        </p>
        <?=
        DetailView::widget([
            'model' => $model,
            'attributes' => [
                'ID',
                'INVENTORY_ID',
                'CHECKIN_TRANSACTION_ID',
                'CHECKOUT_TRANSACTION_ID',
                'SKU',
                'UNIT_PRICE',
                'CREATED_AT',
                'UPDATED_AT',
                'CREATED_BY',
                'UPDATED_BY',
                [
                    'attribute' => 'DELETED',
                    'vAlign' => 'middle',
                    'value' => $model->DELETED == 1 ? 'Deleted' : 'Active',
                ],
                'DELETED_AT',
            ],
        ])
        ?>

    </div>